### ISSUE TITLE
Setting TYPE_IPADDR fails on 64 bit systems (x64 and ARM64)

### ISSUE THREAD

**Issue by darauble** [hleuwer/luasnmp#10]
When setting IP Address via SET method, it fails with an error `wrong length`.

The problem is in this part of the code:

```
case NM_TYPE_IPADDR:
    if (!lua_isstring(L, -1))
      return NULL;
    strval = (char *)lua_tostring(L, -1);
    if ((*((unsigned long *) strbuf) = inet_addr(strval)) == -1)
      return NULL;
    len = sizeof(long);
    break;
```

The problem is that IPADDR should be of 4 byte length, but architecture-dependent `long` is 8 bytes on 64 bit systems and SNMP PDU contains 8 byte zero-padded IP address - checked by network dump.

My local fix was simple:

```
case NM_TYPE_IPADDR:
    if (!lua_isstring(L, -1))
      return NULL;
    strval = (char *)lua_tostring(L, -1);
    if ((*((uint32_t *) strbuf) = inet_addr(strval)) == -1)
      return NULL;
    len = sizeof(uint32_t);
    break;
```

And including <stdint.h>.

**Comment by hleuwer** [comment]
fixed issue in HEAD  - thanks a lot!

**Comment by hleuwer** [comment]
closed

**Comment by darauble** [comment]
I think the fix is not sufficient... len is still `sizeof(long)`, but it should be `sizeof(uint32_t)` to work fully :-D

![image](https://github.com/user-attachments/assets/cff95ef4-f5f1-4a2b-87bb-88cb9c2f0144)

**Comment by hleuwer** [comment]
Did you pull a new version from master branch?
Just now I created a new rock version 1.1.1-1 and uploaded to Luarocks based on master branch or branch 1.1.1-1 in the repositoy.
Please take a look again.

**Comment by darauble** [comment]
Yes, pulled from `master`, switched to `1.1.1-1`:

```
  case NM_TYPE_IPADDR:
    if (!lua_isstring(L, -1))
      return NULL;
    strval = (char *)lua_tostring(L, -1);
    if ((*((uint32_t *) strbuf) = inet_addr(strval)) == -1)   <<< uint32_t - good 
      return NULL;
    len = sizeof(long);     <<<----- long not good :D
    break;
```

**Comment by hleuwer** [comment]
Fix pushed to HEAD and also to luarocks.
Sorry for this - forgot this small part. I actually didn't test this. Thanks for reminding.
