### ISSUE TITLE
luarocks

### ISSUE THREAD

**Issue by tomdaniels41** [hleuwer/luasnmp#9]
Hi, how do i install with luarocks for windows? as it says its not supported/

Thanks

**Comment by hleuwer** [comment]
The rockspec provided only supports Linux or MACOS so far. I do not intend to create a rockspec for WINDOWS. So you have to create your own version for Windows using either CYGWIN or MINGW. 
The README file gives some hints regarding building LUASNMP on WINDOWS.

**Comment by hleuwer** [comment]
Closed.
